### ISSUE TITLE
Using web-ext for easier development on Firefox

### ISSUE THREAD

**Issue by keenjus** [TheUnlocked/Better-Mixer#47]
Since you've added node to the project I thought it would be a good idea to use [web-ext](https://github.com/mozilla/web-ext).

It has a "run" command for quickly launching Firefox with the extension installed + hot-reload that reacts to code changes.

You can close&ignore this if you feel that web-ext is too "bloaty" :)

**Comment by TheUnlocked** [comment]
I was not aware of this. I'll look into it with more detail when I get the time. Couple of quick questions:
1.  Does it support Chromium? I'm assuming not, but I thought I should ask anyways.
2. Does it support automatic rebuild of typescript or frameworks like vue? The reason I've avoided using those until now is because manually rebuilding after every change is slow for development.

**Comment by keenjus** [comment]
1. Sadly no
2. It's not a build system/tool. It just watches the extension directory and refreshes the browser. If you were to add vue/typescript then just point it to the build directory and enjoy hot-reload :)

IIRC Typescript has a `--watch` flag and if you need Vue you should use webpack which also has a `--watch` option for building

**Comment by TheUnlocked** [comment]
Alright. Make a PR and I'll merge it. I'll probably stick with doing development work in Chrome, but if other people want to use Firefox, I'm fine with making their lives easier.

I'll look into gradually updating the codebase to typescript and see what the cost on development is from having a watcher, if any.

**Comment by keenjus** [comment]
I tried experimenting with Typescript (with js support) on my fork. You can take a look if you're interested.

**Comment by TheUnlocked** [comment]
Alright, I'll check it out.
